org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.disableVersionCheck=true
android.suppressUnsupportedOptionWarnings=true
android.enableBuildScriptClasspathCheck=false
android.nonFinalResIds=false
android.nonTransitiveRClass=false
